// vue/vue-vuex/src/components/Count.vue
<template>
    <div class="count">
        <h3>当前求和为：{{sum}}</h3>
        <div class="select">
            请选择每次操作的数值：
            <select v-model.number="n">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
            </select>
        </div>
        <button @click="increment">加{{n}}</button>
        <button @click="decrement">减{{n}}</button>
        <button @click="incrementOdd">当前和为奇数再加{{n}}</button>
        <button @click="incrementWait">等一等再加{{n}}</button>
    </div>
</template>

<script>
export default {
    name: 'Count',
    data() {
        return {
           sum: 0,
           n: 1
        }
    },
    methods: {
        increment() {
            this.sum += this.n;
        },
        decrement() {
            this.sum -= this.n;
        },
        incrementOdd() {
            this.sum = this.sum % 2 !== 0 ? this.sum + this.n :  this.sum;
        },
        incrementWait() {
            setTimeout(() => {
                this.sum += this.n
            }, 500)
        }
    },
}
</script>

<style scoped>
.count {
    width: 300px;
    margin: auto;
}

select, button {
    height: 28px;
}

select {
    width: 80%;
}

.select {
    margin-bottom: 8px;
}
button {
    margin-right: 12px;
    margin-bottom: 8px;
}
</style>

// react/react-redux/src/components/count/index.jsx
import React, { Component } from 'react'
import { Button, Flex, Select } from 'antd';
import './count.css';

export default class Count extends Component {

    state = {
        sum: 0,
        n: 1
    }

    increment = () => {
        const { sum, n } = this.state;
        this.setState({ sum: sum + n })
    }

    decrement = () => {
        const { sum, n } = this.state;
        this.setState({ sum: sum - n })
    }

    incrementOdd = () => {
        const { sum, n } = this.state;
        if (this.state.sum % 2) {
            this.setState({ sum: sum + n })
        }
    }

    incrementWait = () => {
        const { sum, n } = this.state;
        setTimeout(() => {
            this.setState({ sum: sum + n })
        }, 100)
    }

    render() {
        const { n, sum } = this.state;

        return (
            <div className='count'>
                <h1>当前求和为：{sum}</h1>
                <Select
                    defaultValue={1}
                    style={{ width: 350 }}
                    onChange={value => this.state.n = value}
                    options={[
                        { value: 1, label: '1' },
                        { value: 2, label: '2' },
                        { value: 3, label: '3' },
                    ]}
                    className='select'
                />
                <Flex gap="small" wrap>
                    <Button onClick={this.increment}>加{n}</Button>
                    <Button onClick={this.decrement}>减{n}</Button>
                    <Button onClick={this.incrementOdd}>和为奇数加{n}</Button>
                    <Button onClick={this.incrementWait}>异步加{n}</Button>
                </Flex>
            </div>
        )
    }
}
